version: '3.8'

services:

  backend:
    container_name: django
    hostname: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    container_name: postgresql
    hostname: db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env

  cache:
    container_name: redis
    hostname: cache
    image: "redis:6.2-alpine"
    command: redis-server --appendonly yes 
    restart: always
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - ./cache:/data
    ports:
      - "6379:6379"

  scheduler:
    container_name: huey
    hostname: scheduler
    build: ./scheduler
    command: huey_consumer.py scheduler.huey
    restart: always
    env_file:
      - ./scheduler/.env
    volumes:
      - ./scheduler:/usr/src/scheduler
    depends_on:
      - cache

  notifier:
    container_name: notifier
    hostname: notifier
    build: ./notifications
    command: python notifier.py
    restart: always
    env_file:
      - ./notifications/.env
    volumes:
      - ./notifications:/usr/src/notifications
    depends_on:
      - cache

volumes:
  postgres_data: